### ISSUE TITLE
Inconsistency about the object scale in KITTI sequence loader

### ISSUE THREAD

**Issue by nnop** [JingwenWang95/DSP-SLAM#28]
There is some inconsistency between `instance.T_cam_obj` and `instance.scale`.
The object length `l` is used as the scale(L146).

https://github.com/JingwenWang95/DSP-SLAM/blob/ed14d02a55401bfacdcce58547f3cb64a6fcbcbd/reconstruct/kitti_sequence.py#L146-L151

However, it had been enlarged when selecting surface points (**L134**), which is inconsistent with the origin size(L151).

https://github.com/JingwenWang95/DSP-SLAM/blob/ed14d02a55401bfacdcce58547f3cb64a6fcbcbd/reconstruct/kitti_sequence.py#L132-L138

I didn't quantitively evaluate. But fixing this seems making the result better.
![image](https://user-images.githubusercontent.com/23091984/211287829-c4eb1bff-2e58-41d8-bffb-69ed4caaa202.png)

**Comment by JingwenWang95** [comment]
Hi @nnop, Thanks for pointing this out! Using the original length indeed makes more sense!

**Comment by nnop** [comment]
Thanks for the quick confirmation.
