### ISSUE TITLE
how to train custom data？

### ISSUE THREAD

**Issue by Double-zh** [JingwenWang95/DSP-SLAM#5]
Hello, how to train custom datasets, such as fruits?

**Comment by JingwenWang95** [comment]
Hi @Double-zh, generally speaking, to run on your own customized datasets you will need to train 1) 2D detector, 2) DeepSDF, and 3) 3D detector. 
For 2D detector, pre-trained MaskRCNN is usually good enough, or you could fine-tune it on your own dataset, so it won't be a problem. The tricky part might be the DeepSDF model and the 3D detector. 
To train DeepSDF you will need 3D CAD models of the object class that you are interested in. If there are existing datasets of 3D fruits, you can follow the instruction from [DeepSD](https://github.com/facebookresearch/DeepSDF). But you might need to take care of all the data pre-processing and format issues.
For 3D detector, I'd recommend you create your own synthetic images by rendering different view-points and train with your images and gt-poses.
Another issue you need to consider is how you are going to classify the fruit categories. You can train a single DeepSDF model for all fruits categories but I doubt it won't work very well. Anyway, all this depends on your experiments and you need to play with them a little bit. Good luck!
