### ISSUE TITLE
compile failed on "Pangolin make"

### ISSUE THREAD

**Issue by NbbZm** [JingwenWang95/DSP-SLAM#6]
When I run the script , Pangolin install always failed because 'xdg-shell-client-protocol.h' failed.I cant solve it. The reason maybe is I run it on Ubuntu 16,but I cant reproduce in higher version Ubuntu,so anyone can help me? Or can I install Pangolin v0.5 instead of v0.6?

**Comment by JingwenWang95** [comment]
Hi @NbbZm Unfortunately we haven't tested on Ubuntu 16, so I might not provide much help. But Pangolin is only used for visualizing SLAM results and most of my C++ code was borrowed from ORB-SLAM2 which has Ubuntu 16 support. The only tricky part is the object renderer which I wrote myself and I'm not sure it is supported by older version Pangolin. But I'd suggest you try with the older version first. Moreover, this seems more like a Pangolin issue, so I suggest you also have a look at the issues from Pangolin side.

I'm sorry I can't provide too much help with this.
