### ISSUE TITLE
 There is no response after I entering the command~

### ISSUE THREAD

**Issue by QingWind6** [JingwenWang95/DSP-SLAM#8]
Hi,I don't konw why there is no response after typing the command.
Here's the command:./dsp_slam_mono Vocabulary/ORBvoc.bin configs/freiburg_001.yaml freiburg_static_cars_52/car001 map/freiburg/001
The dataset i download is the resulting data which is 4.2GB
Could you help me,please

**Comment by QingWind6** [comment]
I've solved the first problem,but now i make another:
DSP-SLAM: Object Oriented SLAM with Deep Shape Priors.
This program comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it
under certain conditions. See LICENSE.txt.

Input sensor was set to: Monocular

Loading ORB Vocabulary. This could take a while...
Vocabulary loaded!

Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: initfsencoding: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

How can I solve this problem?Thank you~

**Comment by JingwenWang95** [comment]
Hi @QingWind6, please refer to this issue #4

**Comment by QingWind6** [comment]
Thanks！I have fixed all the issues and run it successfully!
